-- Script SQL pour annuler les modifications de la table rooms (ROLLBACK)
-- À utiliser UNIQUEMENT en cas de problème

ALTER TABLE `rooms`
DROP COLUMN `room_category`,
DROP COLUMN `room_subcategory`,
DROP COLUMN `bedding`,
DROP COLUMN `bedding_custom`,
DROP COLUMN `surface_area`,
DROP COLUMN `bathroom_features`,
DROP COLUMN `has_guest_toilet`,
DROP COLUMN `has_additional_bathroom`,
DROP COLUMN `basic_amenities`,
DROP COLUMN `view_type`,
DROP COLUMN `view_price_modifier`,
DROP COLUMN `outdoor_features`,
DROP COLUMN `outdoor_area`,
DROP COLUMN `storage_options`,
DROP COLUMN `has_living_room`,
DROP COLUMN `living_room_features`,
DROP COLUMN `has_kitchen`,
DROP COLUMN `kitchen_type`,
DROP COLUMN `kitchen_equipment`,
DROP COLUMN `has_dining_area`,
DROP COLUMN `dining_capacity`,
DROP COLUMN `additional_bedrooms`,
DROP COLUMN `additional_bedrooms_config`,
DROP COLUMN `premium_amenities`,
DROP COLUMN `paid_options`,
DROP COLUMN `has_private_pool`,
DROP COLUMN `pool_heated`,
DROP COLUMN `has_parking`,
DROP COLUMN `parking_type`,
DROP COLUMN `parking_price`,
DROP COLUMN `is_pmr_accessible`,
DROP COLUMN `pmr_features`,
DROP COLUMN `single_occupancy_price`,
DROP COLUMN `extra_bed_price`,
DROP COLUMN `max_extra_beds`,
DROP COLUMN `custom_tags`,
DROP COLUMN `name_en`,
DROP COLUMN `description_en`;

SELECT 'Rollback réussi : Colonnes supprimées de la table rooms' AS status;
